#!/usr/bin/env bash

# Prowler - the handy cloud security tool (c) by Toni de la Fuente
#
# This Prowler check is licensed under a
# Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
#
# You should have received a copy of the license along with this
# work. If not, see <http://creativecommons.org/licenses/by-nc-sa/4.0/>.

GROUP_ID[99]='platsec'
GROUP_NUMBER[99]='99.0'
GROUP_TITLE[99]='Audit - PLATSEC - [platsec] **********************************'
GROUP_RUN_BY_DEFAULT[99]='Y' # run it when execute_all is called
GROUP_CHECKS[99]='check11,check12,check13,check14,check15,check16,check17,check18,check19,check110,check111,check112,check113,check115,check116,check117,check118,check119,check121,check122,check21,check22,check23,check24,check26,check27,check28,check29,check41,check42,check43,check44'
